spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lc-my/spring-cloud-demo.git
server:
  port: 1201
eureka:
  client:
    service-url: { "defaultZone" : "http://127.0.0.1:8089/eureka/"}